# Generated by Django 5.0.2 on 2025-12-10 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forumpost_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='forks_count',
            field=models.IntegerField(default=0, help_text='Количество форков поста'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='trending_score',
            field=models.FloatField(db_index=True, default=0.0, help_text='Engagement velocity score'),
        ),
    ]
